name: basic
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build && cmake -B build -S . && cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path:
            ./build/tests
            ./build/benches
  
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x tests && ./tests
  
  benches:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x benches && ./benches